# Generated by Django 6.0.7 on 2026-08-04 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('docentes', '0001_initial'),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha del préstamo')),
                ('fecha_devolucion_prevista', models.DateField(blank=True, verbose_name='Fecha prevista de devolución')),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True, verbose_name='Fecha real de devolución')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='alumnos.alumno', verbose_name='Alumno')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='docentes.docente', verbose_name='Docente')),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='libros.ejemplar', verbose_name='Ejemplar')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('alumno__isnull', False), ('docente__isnull', True)), models.Q(('alumno__isnull', True), ('docente__isnull', False)), _connector='OR'), name='prestamo_un_solo_beneficiario'), models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('ejemplar',), name='ejemplar_unico_prestamo_activo')],
            },
        ),
    ]
