# Generated by Django 6.0.7 on 2026-08-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Número de cédula')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área o departamento')),
                ('especialidad', models.CharField(choices=[('ELECTRÓNICA', 'Electrónica'), ('ELECTRICIDAD', 'Electricidad')], max_length=20, verbose_name='Especialidad')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('turno', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=10, verbose_name='Turno')),
                ('activo', models.BooleanField(default=True, verbose_name='Docente activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
