# Generated by Django 6.0.7 on 2026-08-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('ELECTRÓNICA', 'Electrónica'), ('ELECTRICIDAD', 'Electricidad')], default='', max_length=20, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='turno',
            field=models.CharField(blank=True, choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], default='', max_length=10, verbose_name='Turno'),
        ),
    ]
