# Generated by Django 6.0.7 on 2026-08-02 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(blank=True, max_length=200, verbose_name='Autor')),
                ('editorial', models.CharField(blank=True, max_length=150, verbose_name='Editorial')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='ISBN')),
                ('edicion', models.CharField(blank=True, max_length=50, verbose_name='Edición')),
                ('anio_publicacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de publicación')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Estante o ubicación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o resumen')),
                ('activo', models.BooleanField(default=True, verbose_name='Libro activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo', 'autor'],
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='Código CCTL')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('DETERIORADO', 'Deteriorado'), ('EXTRAVIADO', 'Extraviado'), ('BAJA', 'Dado de baja')], default='DISPONIBLE', max_length=20, verbose_name='Estado de circulación')),
                ('condicion', models.CharField(choices=[('NUEVO', 'Nuevo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('DETERIORADO', 'Deteriorado')], default='BUENO', max_length=20, verbose_name='Condición física')),
                ('forma_adquisicion', models.CharField(choices=[('COMPRA', 'Compra'), ('DONACION', 'Donación'), ('TRANSFERENCIA', 'Transferencia'), ('OTRO', 'Otro'), ('NO_ESPECIFICADA', 'No especificada')], default='NO_ESPECIFICADA', max_length=20, verbose_name='Forma de adquisición')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejemplares', to='libros.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Ejemplar',
                'verbose_name_plural': 'Ejemplares',
                'ordering': ['codigo'],
            },
        ),
    ]
