# Generated by Django 6.0.7 on 2026-08-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_ejemplar_options_remove_ejemplar_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionLibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('huella_archivo', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Identificador del archivo')),
                ('titulos_creados', models.PositiveIntegerField(default=0, verbose_name='Títulos creados')),
                ('ejemplares_creados', models.PositiveIntegerField(default=0, verbose_name='Ejemplares creados')),
                ('codigos_reasignados', models.PositiveIntegerField(default=0, verbose_name='Códigos reasignados')),
                ('registros_sin_ubicacion', models.PositiveIntegerField(default=0, verbose_name='Registros sin ubicación')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de importación')),
            ],
            options={
                'verbose_name': 'Importación de libros',
                'verbose_name_plural': 'Importaciones de libros',
                'ordering': ['-fecha_importacion'],
            },
        ),
    ]
