# Generated by Django 6.0.7 on 2026-08-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_importacionlibros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='libro',
            name='area',
            field=models.CharField(blank=True, choices=[('GENERALIDADES', 'Generalidades'), ('FILOSOFIA', 'Filosofía y Psicología'), ('RELIGION', 'Religión'), ('CIENCIAS_SOCIALES', 'Ciencias Sociales'), ('LENGUA_IDIOMAS', 'Lengua e Idiomas'), ('CIENCIAS_NATURALES', 'Ciencias Naturales'), ('MATEMATICA', 'Matemática'), ('TECNOLOGIA', 'Tecnología'), ('ELECTRICIDAD', 'Electricidad'), ('ELECTRONICA', 'Electrónica'), ('INFORMATICA', 'Informática'), ('ARTES', 'Artes'), ('LITERATURA', 'Literatura'), ('HISTORIA_GEOGRAFIA', 'Historia y Geografía'), ('REFERENCIA', 'Referencia'), ('OTRO', 'Otro')], max_length=30, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='libro',
            name='clasificacion',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='libro',
            name='clave_autor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Clave del autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='clave_titulo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Clave del título'),
        ),
        migrations.AddField(
            model_name='libro',
            name='signatura_topografica',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, verbose_name='Signatura topográfica'),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('REPARACION', 'En reparación'), ('DETERIORADO', 'Deteriorado'), ('EXTRAVIADO', 'Extraviado'), ('BAJA', 'Dado de baja')], default='DISPONIBLE', max_length=20, verbose_name='Estado de circulación'),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='proveedor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Proveedor o procedencia'),
        ),
    ]
