# Generated by Django 6.0.7 on 2026-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_remove_libro_categoria_libro_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='etiqueta_lomo_impresa',
            field=models.BooleanField(default=False, verbose_name='Etiqueta de lomo impresa'),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='fecha_impresion_etiqueta_lomo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de impresión de etiqueta de lomo'),
        ),
    ]
