# Generated by Django 6.0.7 on 2026-08-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_ejemplar_etiqueta_lomo_impresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='etiqueta_impresa',
            field=models.BooleanField(default=False, verbose_name='Etiqueta interior impresa'),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='fecha_impresion_etiqueta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de impresión de etiqueta interior'),
        ),
    ]
