# Generated by Django 6.0.7 on 2026-08-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Número de cédula')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('curso', models.CharField(max_length=50, verbose_name='Curso')),
                ('seccion', models.CharField(blank=True, max_length=20, verbose_name='Sección')),
                ('especialidad', models.CharField(blank=True, max_length=100, verbose_name='Especialidad')),
                ('turno', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=10, verbose_name='Turno')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Alumno activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
