# Generated by Django 6.0.7 on 2026-08-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellidos', 'nombres', 'nombre_completo'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='turno',
            field=models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], default='MAÑANA', max_length=10, verbose_name='Turno'),
        ),
    ]
