# Generated by Django 6.0.7 on 2026-08-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_options_alumno_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre_completo', 'apellidos', 'nombres'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
    ]
