# Generated by Django 6.0.7 on 2026-08-18 13:42

import alumnos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumno_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_origen', models.PositiveSmallIntegerField(verbose_name='Año de origen')),
                ('anio_destino', models.PositiveSmallIntegerField(unique=True, verbose_name='Año de destino')),
                ('alumnos_primero_a_segundo', models.PositiveIntegerField(default=0, verbose_name='Promovidos de primero a segundo')),
                ('alumnos_segundo_a_tercero', models.PositiveIntegerField(default=0, verbose_name='Promovidos de segundo a tercero')),
                ('alumnos_egresados', models.PositiveIntegerField(default=0, verbose_name='Alumnos egresados')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ejecución')),
            ],
            options={
                'verbose_name': 'Promoción anual',
                'verbose_name_plural': 'Promociones anuales',
                'ordering': ['-anio_destino'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='anio_egreso',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Año de egreso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='anio_lectivo',
            field=models.PositiveSmallIntegerField(db_index=True, default=alumnos.models.anio_actual, verbose_name='Año lectivo'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre completo'),
        ),
    ]
